# Generated by Django 2.0.2 on 2018-06-19 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('street_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_total_units', models.IntegerField()),
                ('site_floors', models.IntegerField()),
                ('site_prime', models.IntegerField()),
                ('site_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Address')),
                ('site_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('site_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('site_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('unit_floor', models.IntegerField()),
                ('unit_type', models.IntegerField()),
                ('unit_details', models.TextField()),
                ('unit_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='core.Address')),
                ('unit_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site', to='core.Site')),
            ],
        ),
    ]
